
project_name: "Hospital_simulator"

rooms:
  scanner:
    position_x: 2
    position_y: 2
    position_z: 0
    color: "red"
  salle_attente:
    position_x: 5
    position_y: 5
    position_z: 2
    color: "yellow"
  bloc_operatoire:
    position_x: 8
    position_y: 2
    position_z: 4
    color: "green"
  irm_room:
    position_x: 10
    position_y: 8
    position_z: 3
    color: "blue"

groups:
  - group_name: "Equipe Bleue"
    num_people: 5
    color: "blue"
    path: ["scanner", "salle_attente", "bloc_operatoire", "irm_room"]
    room_times:
      - time_in_scanner: 50
      - time_in_salle_attente: 100
      - time_in_bloc_operatoire: 80
      - time_in_irm_room: 120

  - group_name: "Team 123"
    num_people: 3
    color: "green"
    path: ["salle_attente", "bloc_operatoire", "scanner", "irm_room"]
    room_times:
      - time_in_salle_attente: 80
      - time_in_bloc_operatoire: 60
      - time_in_scanner: 90
      - time_in_irm_room: 100

close_delay: 5
